### ISSUE TITLE
Behaviours list separated as characters

### ISSUE THREAD

**Issue by Kittiwork** [olivierfriard/behatrix#3]
Hey, we are having the issue that our behavioural string is being separated out into individual characters rather than the behaviours.  Had this issue on 2 different machines. Any advice please? 
<img width="1377" alt="Screenshot 2024-09-18 at 18 30 16" src="https://github.com/user-attachments/assets/e0671a3e-0135-422a-9a33-b38077bcd636">

**Comment by olivierfriard** [comment]
Hi,
you should type the behavior delimiter in the **Behavior delimiter** field.
I think it is "|" in your case.

Please refer to https://github.com/olivierfriard/behatrix/blob/master/README.rst

**Comment by Kittiwork** [comment]
Evening Olivier. This is great, all working now.  Thanks so much. 
Amanda

**Comment by Kittiwork** [comment]
Hello again Olivier

Sorry to bother you again.  I dont suppose there is a way to bulk edit modifiers in an observation? I.e. if you changed the names of your modifiers on an observation you already completed.  At the moment I am doing each one separately under Edit Selected Event, which gets me through to the modifier screen to edit it. But is if possible to select all events with the same modifier and change them? 

Many thanks

Amanda

**Comment by Kittiwork** [comment]
Apologies Olivier, I have just found the answer. Thanks
